name: Build

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: install and build
        run: |
          npm install
          npm run build:all
